# Generated by Django 4.2 on 2023-05-29 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_options_alter_achievements_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='education_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_stage', to='students.educationform'),
        ),
    ]
