# Generated by Django 4.2 on 2023-05-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_education_form_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='code',
        ),
    ]
